In [1]:
import numpy as np


In [4]:
np.array((2,3,4))

array([2, 3, 4])

In [6]:
np.array([(2.0,3),(4,5)])

array([[2., 3.],
       [4., 5.]])

In [7]:
np.array([(2.0,"three"),(4,5)])

array([['2.0', 'three'],
       ['4', '5']], dtype='<U32')

In [8]:
np.random.random((2,4))

array([[0.79893828, 0.74662058, 0.77304303, 0.11736281],
       [0.24685029, 0.27903603, 0.96616952, 0.49258605]])

In [9]:
np.arange(2,3,.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [12]:
np.linspace(1,6,num=10,endpoint=False)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [13]:
float(np.array((2,3,4)))

TypeError: only size-1 arrays can be converted to Python scalars

In [14]:
a1 = np.array([1,2,3,4,5])
a2 = a1[2]
a2 

3

In [ ]:
a1 = np.array([1,2,3,4,5])
a2 = a1[2]
a3 = a1[-2]
